language: java

sudo: required
jdk:
  - openjdk11

services:
  - docker



before_install:
  - chmod +x mvnw
  - chmod +x start_crashtest.sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_PASSWORD" | docker login --username="$HEROKU_USERNAME" --password-stdin registry.heroku.com
  - heroku auth:token

addons:
    sonarcloud:
        organization: "devsecopslocalidosos"
        token:
            secure: Rah/OHnpHZEiiF0fnOcvdfmXHvDnLhiFeHA0GfeVM+DKKTjWuh1ucxNNl2JvmXsj2ED/3zbvqN3+sv4VHKDevdyJXWvSZ8CMHXtVBwgOA7tjHA4efCSY71+6sQlMd0Y3rygaT1hnIVGY8XejY/OQe4281U8Ep0eahxV3oepEktpe/PLTVuPM483SlvSe6Z284pdJm+TjuirWCjoY23kNGpuwOmmoqhKJ/Dtau0jft2nj/aekxx7DO1Ipoh7ReUxA7jmTP3Me0P1tfrEKn/agHzQaHezse+eySjs+6zPCXDqC4TaE/kSsLAbM/RyA3UwlkchxEfBDZ4JiSMvwZqs+e4AUC05qy367MMqXKvhKAGTrSxny0C5PECryGL7oZOBSdeAxOqkKohr0Y48gTKBeALmy5TvnH73UIBx3IzkOe750Gf3CZoR5svwzrCJGIje73tIkDu9nZ8rcKbwrSny0Mm9tqrttmwNrI2/7F6Bx9BxYvX2m4R3ZucikuorQ6LEbUoQ7cP4+hhs0jk/sTwWflyB0bTRLisp5AvJJnSR8P8x/aUAoZstB0QOFdHZ2AgqD3Ua95ACCq/k2rgdwOXJHWWIUChn1RTDLiHy7zk/q3o58HDRwEtJe1xtzxig3SifOoLFBE5cStz5juA0fv35ULbP7W7ykuHOwqPP0vgaveac=
jobs:
  include:
    - stage: build
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t travis-ci-build-stages-demo -f Dockerfile.dev .
        - docker images
        - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
        - docker build -t $DOCKER_USERNAME/$HEROKU_APP_NAME -f Dockerfile .
        - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
        - docker images
        - docker tag $DOCKER_USERNAME/$HEROKU_APP_NAME registry.heroku.com/$HEROKU_APP_NAME/web
        - docker push $DOCKER_USERNAME/$HEROKU_APP_NAME
        - heroku container:push web --app $HEROKU_APP_NAME
        - heroku container:release web --app $HEROKU_APP_NAME

notifications:
  slack: devsecopsloscalidosos:hgUQd6hu0cDRbtA3Ig1V1TN0
#    on_success: always  # change: send a notification when the build status changes.
#    on_failure: always  # always: always send a notification.
#    if: branch = master