language: java

sudo: required

services:
  - docker

env:
  global:
    - secure: "m+/CH8BTFruGF7Bg2hrf7D+kX6Zz3Bp6DHSe75jy0tGiyPFMERdL+axxKlpcQodMzRvqmY0LNa3fv9UJkSAht5j86JEGFefxRzHMb8nwGMsv/lWvSZp0xIZmWL76Vtw6QBl9HIxjnICN5JmM6urMvKHI0qU7wMsfESBlBxuhc7LDG6YXcN1I1+DdHMgoAGadIXScvRzzwA3+79A1dw9NvTlqKUJUcWoviySTn4SxCbEs19y4HBW9GHoWVVZ2PuUh1kfKl3XnjaZkwxK/tgs9J1KCw0albNOXQ7Q46uhdwKdN7TBneqSEa20DLvaYYa1yRY+RxS76HIN2MeeQ5V2hufCOlN1z/NIxKopGWfH8K6MSokQRIUZNbnKp7SSvmaOb6o60s63vqSH1xmJukFTnHFHwyY7VqZMwqeHsvczMNSdRMJfiKysRdjRLWTOMYs5IR+08Xdhd9TdtSp0wRI4iU4/9/liaBF2XgttjA3Ox561KkXI3/4yxaW4CpRTsRpdyW7N7O2SAk7s127WRDze94UvXtSNf7XvjuawVQ5Wu+JdC3PBu34xAqORsIeERy5ZjorHzMysgwcl8xD19JFUyx7uchoPOhO6D/i7JyTRied6t7JaBAqxnGmzC+AmfSf7XuaG4iFrX1+EsbcCV9Y+1D1OqnRbedszfLydPyyhMIxw="
    - secure: "mZ6hj6aeAOqXVpeDBLmkxtya8HMnvBrd6LO5ZBL6L9I6vQX8vouP818q9srUk+kAonlLQ9zTSFxrzbx6wyJiCPbosM7gRnny7tsucJzVzHy9mhoNDLzXwFSucs+BdCOK/4DihbiROeT7icNJknE+R0tSNr50AR72+SnIsBuAhRph6G6jMLB5+9KnYspsey9CjVYtNrK3TIYxcib9OpMiii4Ma9q9oWdkrtrMTBTB4uIK3voMY6I16+bEYuEmVbKtnazkTSR39S5W6TS3cmjOnLZ+75vKyGZGfuFl4dxBZNBVlQ19OLVZ0sjtaFgV4Yyr9a1kZj1XX+u0jkV6oSDr3bJDPRru1396DhRbOw/nQ4ZMTuqR4+iBXYSIVWbgjMY5H8FACPPPJvLtGYGsiwGOryfFv408gwpzkZTc0l91qxzs0qXvdW+X1f5VX83g5o1TrT44+Vd2kWBBFZYPDVuxjMhz4DHSEbK0uHI7uIEEyCO2GFVpZABoX0+DXIMVFugWD5uKZ5+7Aq5skom3hqA1fb2E4nleJIUQvWTVCBRnlLRbUc56GCofEI0zkTbIFaG1Mh0Kkye+/UeJgs6riI3huFWWe40RWFJqyyIQpoUHWnp6BvsHceAIQf6o6ya9PA33X9m8ZYus4p30r7aX1maQjoBe+oRybbT+qs3PeriLbdc="
    - secure: "kOoW1yNsUwUpoeL3QrbWCiWZ4K7H2UHryV3KFMtTB16nElL4WO1smil1i199YW4k+grOQoNgqAV229ANnkATosCrBP1+gfnSh7/MOSp8AE6qH+mnhIv7ASyE2kOavYLMt9ywxvN4c5ryFI456erZ5WNBFEU9AJkSQ++OxqpTxsmmEgrGkp37E4fJB7Ctkb1RCQ9IiQ/REL1dn2Y508rTSaE7UCHG9IdeHUTzP8val0t5pcLRUsc8Y55pufpppmJy1G0mdJ2K3BL1GJN9NtN+QqaUcY1QO2FdW4KFQ3bITs3eGw0n8OmJHqBdFIxVfmZ3mHAcNqQRhpCT8/aSCakkwdLYI/yqsYlvSilimvDKHfDbLjOq9p7Ek0zA+VJp2iL1ujOmGJXCEQgteLxvWYk/iCGs8SjAGSLT00fEZysnuWbzBV7UoG6a0DOFcyu2TmcGw+bg8iwlDdTYptdbp2Gn5GDgqvIF+yVf7q+MTHRxvjG9ndQhBS5axrotfe5M1QDhIiqZcwjza6a4L3CdwMMLKYMcFBBxKihqQrkRPxgkw6MppyFdjshB4wpePCb+Vx1HJZC0VxDmMSRTkrhCw/sKuc9WWH56Pxi37XYI4Zwahgjj58EnXvv+3NRUlo7n1rTW7wtZrNLHRo06FSha9ip2Lpzf7waLKqF9f7oy7DPuSb4="
    - secure: "ortNag+otVPNDWtCeMuGSZXw8x6onHFa9gpGLypDw7ec+zesGy/By0CmLuaQnnBq6O+vTSkhT+mF+ZAL/oVS+OL30kApH6hm1ieQ4VtZM0YqsIN0YejQWz2uIYXIYhy0v6F3a7mR0C/SJmGW8U7VhESSUiQ9b7X7Wqw54gZNNPChSfzwRN4iam/hxUTYgDjUUFYJ2C9tmV0hHmqIU5+Ap1KORwfjaVWX1nZQBHRB1RfyzRKxL4DBVQkiHgEe8arO3g39lOvaavgzRIc3P9WqJ5/lY95fDX3Y1Li0IXw1Dj7quBGpNE6HW/oNqpQxUM+7bH8SGKtWPU0+fwR61YmM6zBcrH2zbvGL7bY7Blfhl9P048EWlDcjkVSyYBhgoJWlxApUhh8VjQdsZrixW5OjyhybHXn02lXhUmSFWZ8xbofDTgS5HvZEK9BrqRMDWoCgVMezei0XAxhcPOUZrUpk4/nYFAbHJJAfZg/xM5I3zfqR8eCEkg66BYrKIsIktDWOndzG4oKur0i//hA+urkkQilIAUwpb1Y45hC8B4GOvwOaZNdNU1gyOI+89qiwo//ktqMQjsEuaQQMrZUEWTKGcsqFLy92FGZR6bYZ3WCKEQZC8IZECdzXFwq/suaRoplCMUsDEP1KPiDHuwyVRfdCUWiUxShAziOWQhingMS4OnY="
    - secure: "AL7jTjShjLVJgDae3DGdkiaYmSUkMDhf3tBeBZH3uQcY94orQl/MhFaVy3Kp05PFy2fz7jj+lzPqK3PghlyLyX7BRPmSx8UsBinHFRoeBJ7rwv65RdqA0FMmIsNxTJwnDru+r0lWjl7mWHOh4u2UfeNzDZJ6D7/xKqy9/Ml6kvgIGVFXSzDRqN9Hf/xK/0p9bKkU5nMdvDVUXYa/D5dCD8Ki6OkzHTZGChE4uBO5/bIgPPyDlJpulPh63MbLv+0xEI/WAu+whjbA5aOpZVsElH9qfH5IUH6LQtuenG2U47uGLu0lbKjKd/IFV/gP2whDbvNPXGnNttfBFoqP6xUllxIrjNSwW26XKyyjX3n/bJGouDvdTDskWoeB5eoiy+wMcwZojSYxF6l+Tdr3fdeyq3SOxas+yCfJyqw+0/VZuAeLu0MvtbmFvK+1cbX91/eSdvQfVv9xYqluyh4IgIm8p+M5TRBwQBS5y8oD6LbdTa2xozDJpvVDKmxpRsKq+ZeXHVjeVL/scyPwrM4UuuOQD27ovdKHfnaQnkkL9JOaeGC+dU5pk2tuLZiu0OaBxsVOeCtjV/RzMsV4WjuV0NrPo+qXdDL+LZPSS51X73uaDFtZZHHqGorJ7QLG6javbsczeYQaxcSrGGpUBgGDNPqt9Y7KWJHjOsiVJ10cmnnOH3c="
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  - chmod +x mvnw
  - chmod +x start_crashtest.sh
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin registry.heroku.com


addons:
    sonarcloud:
        organization: "devsecopslocalidosos"
        token:
            secure: Rah/OHnpHZEiiF0fnOcvdfmXHvDnLhiFeHA0GfeVM+DKKTjWuh1ucxNNl2JvmXsj2ED/3zbvqN3+sv4VHKDevdyJXWvSZ8CMHXtVBwgOA7tjHA4efCSY71+6sQlMd0Y3rygaT1hnIVGY8XejY/OQe4281U8Ep0eahxV3oepEktpe/PLTVuPM483SlvSe6Z284pdJm+TjuirWCjoY23kNGpuwOmmoqhKJ/Dtau0jft2nj/aekxx7DO1Ipoh7ReUxA7jmTP3Me0P1tfrEKn/agHzQaHezse+eySjs+6zPCXDqC4TaE/kSsLAbM/RyA3UwlkchxEfBDZ4JiSMvwZqs+e4AUC05qy367MMqXKvhKAGTrSxny0C5PECryGL7oZOBSdeAxOqkKohr0Y48gTKBeALmy5TvnH73UIBx3IzkOe750Gf3CZoR5svwzrCJGIje73tIkDu9nZ8rcKbwrSny0Mm9tqrttmwNrI2/7F6Bx9BxYvX2m4R3ZucikuorQ6LEbUoQ7cP4+hhs0jk/sTwWflyB0bTRLisp5AvJJnSR8P8x/aUAoZstB0QOFdHZ2AgqD3Ua95ACCq/k2rgdwOXJHWWIUChn1RTDLiHy7zk/q3o58HDRwEtJe1xtzxig3SifOoLFBE5cStz5juA0fv35ULbP7W7ykuHOwqPP0vgaveac=
script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=enriquedurango2019/devopsloscalidosos
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME
  - heroku container:push --recursive

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: devsecopsloscalidososkdj1
